local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
amazon:
  service: S3
  access_key_id: "AKIA3PWIUNLHO7BHCMMG"
  secret_access_key: "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"
  bucket: "zonankalaloo"
  region: "us-east-2"
  # access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  # secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
